#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

#Requirements:

#Install nginx on your web-01
#server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
#As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
#You can’t use systemctl for restarting nginx

apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
rewrite="server {
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
	location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

echo -e "$rewrite" > /etc/nginx/sites-available/redirect
ln -sf /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
sudo nginx -t
service nginx restart
