#!/usr/bin/env bash
#t configures a brand new Ubuntu machine to the requirements asked in this task

#!/bin/bash

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create the default HTML file
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Add custom header to Nginx
cat <<EOF | sudo tee /etc/nginx/sites-available/custom_header
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        add_header X-Served-By \$hostname;
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Enable the custom header
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Verify the configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
