#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#Requirements:

#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script
#Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
#For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements


sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo  apt-get -y  install haproxy=2.6.\*

# params
domain_name='codewithalareef.tech'
init_file='/etc/default/haproxy'
config_file='/etc/haproxy/haproxy.cfg'


#config
