#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

ln -sf /etc/nginx/sites-available /etc/nginx/sites-enabled/default
sudo service nginx restart
