#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80. Feel free to install whatever tool you need, start and destroy as many containers as you need to debug the issue. Then, write a Bash script with the minimum number of commands to automate your fix.

#Requirements:
#
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
#Write a Bash script that configures a server to the above requirements

sudo echo "server {
    listen 80;
    server_name codewithalareef.tech www.codewithalareef.tech;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html index.test.html;
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
