#!/usr/bin/env bash
#Write a Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function remove_file {
	rm /var/run/myscript.pid 
	exit
}

echo $$ > var/run/myscript.pid 

until false
do
	echo To infinity and beyond
	sleep 2

	trap 'echo "I hate kill command" && remove_file' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'remove_file' SIGQUIT
done
