#!/usr/bin/env bash
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
#Make a copy of your 6-stop_me_if_you_can script, name it 67-stop_me_if_you_can, that kills the 7-highlander process instead of the 4-to_infinity_and_beyond one.

trap "echo I am invincible!!!" SIGTERM
i=0
while [ $i ]
do
	echo To infinity and beyond
	sleep 2
done
