#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user
# Requirements:
	# You must use the while loop (for and until are forbidden)
# Define the field separator as a colon (:)

IFS=':'

while read -r username groupid homedir shell userid password useridinfo
do
	echo "The user $username is part of the $groupid gang, lives in the $homedir, and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
