#!/usr/bin/env bash

sudo sed -i '/#user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx-conf
pkill apache2
sudo -u nginx service nginx restart
sudo -u nginx service nginx start
