#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client, let’s configure it to our needs so that you can connect to a server without typing a password. Share your SSH client configuration in your answer file.

# Requirements:

# Your SSH client configuration must be configured to use the private key ~/.ssh/school
 # Your SSH client configuration must be configured to refuse to authenticate using a password



#echo "User ubuntu" >> /etc/ssh/ssh_config
#echo "Host 18.209.180.49" >> /etc/ssh/ssh_config
#echo "User ubuntu" >> /etc/ssh/ssh_config
#echo "IdentityFile ~/.ssh/config" >> /etc/ssh/ssh_config
#echo "PasswordAuthentication no" >> /etc/ssh/ssh_config

Host 18.209.180.49
User ubuntu
IdentityFile ~/.ssh/school
PasswordAuthentication no
